# Generated by Django 3.2.3 on 2021-06-01 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accounting', models.IntegerField(default=0)),
                ('Anthropology', models.IntegerField(default=0)),
                ('Appraise', models.IntegerField(default=0)),
                ('Archeology', models.IntegerField(default=0)),
                ('Art_Craft', models.IntegerField(default=0)),
                ('Charm', models.IntegerField(default=0)),
                ('Climb', models.IntegerField(default=0)),
                ('Credit_Rating', models.IntegerField(default=0)),
                ('Cthulhu_Mythos', models.IntegerField(default=0)),
                ('Disguise', models.IntegerField(default=0)),
                ('Dodge', models.IntegerField(default=0)),
                ('Drive_Auto', models.IntegerField(default=0)),
                ('Electric_Repair', models.IntegerField(default=0)),
                ('Fast_Talk', models.IntegerField(default=0)),
                ('Fighting', models.IntegerField(default=0)),
                ('Handguns', models.IntegerField(default=0)),
                ('Rifles_Shotguns', models.IntegerField(default=0)),
                ('First_Aid', models.IntegerField(default=0)),
                ('History', models.IntegerField(default=0)),
                ('Intimidate', models.IntegerField(default=0)),
                ('Jump', models.IntegerField(default=0)),
                ('Other_Language', models.IntegerField(default=0)),
                ('Own_language', models.IntegerField(default=0)),
                ('Law', models.IntegerField(default=0)),
                ('Library_Use', models.IntegerField(default=0)),
                ('Listen', models.IntegerField(default=0)),
                ('Locksmith', models.IntegerField(default=0)),
                ('Mech_Repair', models.IntegerField(default=0)),
                ('Medicine', models.IntegerField(default=0)),
                ('Natural_World', models.IntegerField(default=0)),
                ('Navigate', models.IntegerField(default=0)),
                ('Occult', models.IntegerField(default=0)),
                ('Op_Hv_Machine', models.IntegerField(default=0)),
                ('Persuade', models.IntegerField(default=0)),
                ('Pilot', models.IntegerField(default=0)),
                ('Psychology', models.IntegerField(default=0)),
                ('Psychoanalysis', models.IntegerField(default=0)),
                ('Ride', models.IntegerField(default=0)),
                ('Science', models.IntegerField(default=0)),
                ('Slight_of_hand', models.IntegerField(default=0)),
                ('Spot_hidden', models.IntegerField(default=0)),
                ('Stealth', models.IntegerField(default=0)),
                ('Survival', models.IntegerField(default=0)),
                ('Swim', models.IntegerField(default=0)),
                ('Throw', models.IntegerField(default=0)),
                ('Track', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('player_name', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField()),
                ('residence', models.CharField(max_length=150)),
                ('birthplace', models.CharField(max_length=150)),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('occupation', models.TextField(choices=[('Occupation: Antiquarian. Occupational Skill Point Focus: Appraise, Art/Craft(Any), History, Library Use,Other Language, One interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade), Spot Hidden, any one other Skill. Credit Rating: 30-70 ', 'Antiquarian'), ('Occupation: Author     . Occupational Skill Point Focus: Art/Craft(Literature), History, Library Use, Natural world or Occult, Other language, Own language, Psychology, any one other skill. Credit Rating: 9-30 ', 'Author')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STR', models.IntegerField(default=45)),
                ('DEX', models.IntegerField(default=45)),
                ('INT', models.IntegerField(default=65)),
                ('CON', models.IntegerField(default=75)),
                ('APP', models.IntegerField(default=45)),
                ('POW', models.IntegerField(default=55)),
                ('SIZ', models.IntegerField(default=45)),
                ('EDU', models.IntegerField(default=65)),
                ('LUCK', models.IntegerField(default=35)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideology_beliefs', models.TextField(choices=[('There is a higher power that you worship and pray to', 'There Is A Higher Power That You Worship And Pray To'), ('Mankind can do fine without religions.', 'Mankind Can Do Fine Without Religions'), ('Science has all the answers. Pick a particular aspect of interest. ', 'Science Has All The Answers Pick A Particular Aspect Of Interest'), ('A belief in fate.', 'A Belief In Fate'), ('Member of a society or secret society.', 'Member Of A Society Or Secret Society'), ('There is evil in society that should be rooted out. What is this evil? ', 'There Is Evil In Society That Should Be Rooted Out'), ('The occult.', 'The Occult'), ('Politics.', 'Politics'), ("Money is power, and I'm going to get all I can.", 'Money Is Power And Im Going To Get All I Can'), ('Campaigner/Activist.', 'Campaigner Or Activist')])),
                ('ideology_beliefs_descriptor', models.TextField(max_length=250)),
                ('significant_people', models.TextField(choices=[('Parent.', 'Parent'), ('Grandparent.', 'Grandparent'), ('Sibling.', 'Sibling'), ('Child.', 'Child'), ('Partner.', 'Partner'), ('Person who taught you your highest occupational skill. Identify the skill and consider who taught you. ', 'Person Who Taught You Your Highest Occupational Skill Identify The Skill And Consider Who Taught You'), ('Childhood friend.', 'Childhood Friend'), ('A famous person. Your idol or hero. You may never have even met. ', 'A Famous Person Your Idol Or Hero You May Never Have Even Met'), ('A fellow investigator in your game. Pick on or choose randomly. ', 'A Fellow Investigator In Your Game Pick On Or Choose Randomly'), ('A non-player character in the game. Ask the Keeper to pick one for you.', 'A Non Player Character In The Game')])),
                ('significant_people_descriptor', models.TextField(max_length=250)),
                ('meaningful_locations', models.TextField(choices=[('Your seat of learning.', 'Your Seat Of Learning'), ('Your hometown.', 'Your Hometown'), ('The place you met your first love.', 'The Place You Met Your First Love'), ('A place for quiet contemplation.', 'A Place For Quiet Contemplation'), ('A place for socializing.', 'A Place For Socializing'), ('A place connected with your ideology/belief.', 'A Place Connected With Your Ideology Or Belief'), ('The grave of a significant person. Who?', 'The Grave Of A Significant Person'), ('Your family home.', 'Your Family Home'), ('The place you were happiest in your life.', 'The Place You Were Happiest In Your Life'), ('Your workplace.', 'Your Workplace')])),
                ('meaningful_locations_descriptor', models.TextField(max_length=250)),
                ('treasured_possessions', models.TextField(choices=[('An item connected with your highest skill', 'An Item Connected With Your Highest Skill'), ('An essential item for your occupation', 'An Essential Item For Your Occupation'), ('A memento from you childhood', 'A Memento From You Childhood'), ('A memento of a departed person', 'A Memento Of A Departed Person'), ('Something given to you by your significant person', 'Something Given To You By Your Significant Person'), ('Your collection. What is it', 'Your Collection What Is It'), ('Something you found but you dont know what it is. You seek answers ', 'Something You Found But You Dont Know What It Is You Seek Answers'), ('eight', 'A Sporting Item'), ('A weapon', 'A Weapon'), ('A pet', 'A Pet')])),
                ('treasured_possessions_descriptor', models.TextField(max_length=250)),
                ('traits', models.TextField(choices=[('Generous', 'Generous'), (' Good with animals', 'Good With Animals'), ('Dreamer', 'Dreamer'), ('Hedonist', 'Hedonist'), ('Gambler and risk taker', 'Gambler And Risk Taker'), ('Good cook', 'Good Cook'), ("Ladies' man/seductress", 'Ladies Man Or Seductress'), ('Loyal.', 'Loyal'), ('A good reputation', 'A Good Reputation'), ('Ambitious', 'Ambitious')])),
                ('traits_descriptor', models.TextField(max_length=250)),
                ('personal_description', models.TextField(max_length=300)),
                ('injuries_scars', models.CharField(max_length=250)),
                ('phobias_Manias', models.CharField(max_length=250)),
                ('arcane_tomes_spells_artifacts', models.CharField(max_length=250)),
                ('encounters_with_strange_entities', models.CharField(max_length=250)),
                ('select_a_key_connection_from_above', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
