# Generated by Django 3.2.3 on 2021-06-04 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('char', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='APP',
            field=models.IntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='DEX',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='EDU',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='INT',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='LUCK',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='POW',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='SIZ',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='STR',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='charbasicinfo',
            name='occupation',
            field=models.TextField(choices=[('Occupation: Antiquarian. Occupational Skill Point Focus: Appraise, Art/Craft(Any), History, Library Use,Other Language, One interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade), Spot Hidden, any one other Skill. Credit Rating: 30-70 ', 'Antiquarian'), ('Occupation: Author.    Occupational Skill Point Focus: Art/Craft(Literature), History, Library Use, Natural world or Occult, Other language, Own language, Psychology, any one other skill. Credit Rating: 9-30 ', 'Author')]),
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hand_to_Hand_Weapon', models.CharField(default='None', max_length=100)),
                ('Hand_to_Hand_Weapon_Damage', models.CharField(default='None', max_length=100)),
                ('Handgun', models.CharField(default='None', max_length=100)),
                ('Handgun_Damage', models.CharField(default='None', max_length=100)),
                ('Shotgun', models.CharField(default='None', max_length=100)),
                ('Shotgun_Damage', models.CharField(default='None', max_length=100)),
                ('Rifle', models.CharField(default='None', max_length=100)),
                ('Rifle_Damage', models.CharField(default='None', max_length=100)),
                ('Automatic_Weapon', models.CharField(default='None', max_length=100)),
                ('Automatic_Weapon_Damage', models.CharField(default='None', max_length=100)),
                ('Misc', models.CharField(default='None', max_length=100)),
                ('Misc_Damage', models.CharField(default='None', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashAndAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cash', models.IntegerField()),
                ('Assets', models.IntegerField()),
                ('Spending_level', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
