# Generated by Django 3.2.3 on 2021-06-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char', '0003_auto_20210604_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backstory',
            name='arcane_tomes_spells_artifacts',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='backstory',
            name='encounters_with_strange_entities',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='backstory',
            name='injuries_scars',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='backstory',
            name='phobias_Manias',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='APP',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='CON',
            field=models.IntegerField(default=85),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='DEX',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='EDU',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='LUCK',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='POW',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='SIZ',
            field=models.IntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='STR',
            field=models.IntegerField(default=50),
        ),
    ]
