# Generated by Django 3.2.3 on 2021-06-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('char', '0006_auto_20210604_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backstory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char.charbasicinfo'),
        ),
        migrations.AlterField(
            model_name='cashandassets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char.charbasicinfo'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='APP',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='CON',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='DEX',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='INT',
            field=models.IntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='LUCK',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='POW',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='SIZ',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='STR',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char.charbasicinfo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char.charbasicinfo'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char.charbasicinfo'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char.charbasicinfo'),
        ),
    ]
