# Generated by Django 3.2.3 on 2021-06-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char', '0008_auto_20210607_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='Art_Craft_Chosen',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='skills',
            name='Other_Language_Chosen',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='skills',
            name='Science_chosen',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='APP',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='CON',
            field=models.IntegerField(default=35),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='DEX',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='EDU',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='INT',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='LUCK',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='SIZ',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='STR',
            field=models.IntegerField(default=25),
        ),
    ]
