# Generated by Django 3.2.3 on 2021-06-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('char', '0018_auto_20210610_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='Piloting',
            new_name='Piloted_Vehicle',
        ),
        migrations.AlterField(
            model_name='backstory',
            name='ideology_beliefs_descriptor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='backstory',
            name='meaningful_locations_descriptor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='backstory',
            name='personal_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='backstory',
            name='significant_people_descriptor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='backstory',
            name='traits_descriptor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='backstory',
            name='treasured_possessions_descriptor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='APP',
            field=models.IntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='CON',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='DEX',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='EDU',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='INT',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='LUCK',
            field=models.IntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='POW',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='SIZ',
            field=models.IntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='STR',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='charbasicinfo',
            name='occupation',
            field=models.TextField(choices=[('Occupation: Antiquarian. Occupational Skill Point Focus: Appraise, Art/Craft(Any), History, Library Use,Other Language, One interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade), Spot Hidden, any one other Skill. Credit Rating: 30-70 ', 'Antiquarian'), ('Occupation: Author.    Occupational Skill Point Focus: Art/Craft(Literature), History, Library Use, Natural world or Occult, Other language, Own language, Psychology, any one other skill. Credit Rating: 9-30 ', 'Author'), ('Occupation: Dilettante. Occupational Skill Point Focus: Art/Craft(Any), Fire Arms, Other Languages, Ride, One interpersonal skill(Charm, Fast Talk, Intimidate, or Persuade), Any three other skills. Credit Rating: 50-99', 'Dilettante'), ('Occupation: Doctor.    Occupation Skill Point Focus: First Aid, Other Language (Latin)Medicine, Psychology, Science (Biology), Science (Pharmacy), any two other skills as academic or personal specialties (e.g. a psychiatrist might take psychoanalysis). Credit Rating: 30-80', 'Doctor Of Medicine'), ('Occupation: Journalist. Occupational Skill Point Focus: Art/Craft(Photography), History, Library Use, Own Language, one interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade),Psychology, any two other skills. Credit Rating: 9-30', 'Journalist'), ('Occupation: Detective. Occupational Skill Point Focus: Art/Craft(Acting), or Disguise,Firearms, Law, Listen, one interpersonal skill(Charm, Fast Talk, Intimidate, or Persuade), Psychology, Spot Hidden, any one other skill. Credit Rating: 20-50', 'Police Detective'), ('Occupation: P.I.       Occupational Skill Point Focus: Art/Craft(Photography), Disguise,Law, Library Use, one interpersonal skill (Charm, Fast Talk, Intimidate, or Persuade)Psychology, Spot Hidden and any one other skill(e.g. Lock Smith, Firearms) Credit Rating: 9-30', 'Private Investigator'), ('Occupation: Professor. Occupational Skill Point Focus: Library Use, Other Language, Own Language,Psychology, any four other skills as academic or personal specialities. Credit Rating: 20-70', 'Professor')]),
        ),
    ]
